version: '3'

services:
  database:
    image: postgres:10.17
    environment:
     - "POSTGRES_USER=lucasdavila"
     - "POSTGRES_PASSWORD=radiotvnews"
     - "POSTGRES_DB=inssueapp"
    ports:
     - 5441:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  pg-data:
